FROM node:13.12.0-alpine

ARG PROGRAM_ADDRESS
ENV ENV_PROGRAM_ADDRESS=$PROGRAM_ADDRESS

ARG ENVIRONMENT
ARG ENV_ENVIRONMENT=$ENVIRONMENT

WORKDIR /app

COPY . .

RUN yarn install --silent
RUN yarn install react-scripts@3.4.1 -g --silent

RUN REACT_APP_CLUSTER=$ENV_ENVIRONMENT REACT_APP_PROGRAM_ID=$ENV_PROGRAM_ADDRESS yarn run build --production

RUN yarn install -g serve

CMD serve -p 8080 -s build

EXPOSE 8080
