name: CICD

on:
  push:
    branches:
    - localnet
    - devnet
    - mainnet
    - github-pages
  pull_request:

env:
  # use docker.io for Docker Hub if empty
  REGISTRY: us.gcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}
  # repository name without account name
  REPOSITORY_NAME: ${{ github.event.repository.name }}

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install dependencies
        run: yarn install
      - name: Run tests
        run: yarn test

  cd-devnet:
    runs-on: ubuntu-latest
#    if: github.ref == 'refs/heads/devnet' || github.ref == 'refs/heads/mainnet'
    needs: [ci]
    environment:
      name: devnet
      url: https://app.dev.credix.finance
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install and build
        run : |
          yarn install --silent
          yarn global add react-scripts@3.4.1 --silent
          REACT_APP_CLUSTER=devnet REACT_APP_PROGRAM_ID=${{ secrets.PROGRAM_ADDRESS }} yarn run build --production
      - name: Checkout target repository
        uses: actions/checkout@v2
        with:
          repository: credix-finance/credix-app-devnet
          path: 'deploy'
      - name: Push files to target repository
        run: |
          cp -r build/dist/* deploy
          cd deploy
          echo ${{ secrets.DEPLOY_URL }} > CNAME
#          git add .
#          git commit -m $GITHUB_SHA
#          git push
